# System configuration
---
version: '1'

system:
  defaults:
    driver: jenkins
    showJobOutput: false
    showJobOutcome: true
    runAsTriggerUser: false

    options:
      myVar:
        value: someDefaultValue

  requestHeaders:
    Cookie: "foo=bar"
